services:
  postgres:
    image: postgres:16-alpine
    container_name: voice_bot_postgres
    environment:
      POSTGRES_DB: video_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./PROJECT_12_VOICE_BOT_VIDEO_SQL/postgres/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d video_analytics"]
      interval: 5s
      timeout: 3s
      retries: 10

